.Dd $Mdocdate: March 29 2022 $
.Dt SHAPPY 1
.Os
.Sh NAME
.Nm shappy
.Nd create snapshots and clean up unused ones
.Sh SYNOPSIS
.Nm shappy <snapshot|cleanup>
.Sh DESCRIPTION
.Pp
\fBShappy\fR makes snapshotting of ZFS easy. All configuration is kept in ZFS
attributes:
.Pp
.Bl -tag -width Fa -compact
.It Cm snapshot:on
Any value except "yes" skips the dataset completely
.It Cm snapshot:daily=<number>
Number of daily snapshots to keep
.It Cm snapshot:weekly=<number>
Number of weekly snapshots to keep
.It Cm snapshot:monthly=<number>
Number of montly snapshots to keep
.It Cm snapshot:yearly=<number>
Number of yearly snapshots to keep
.El
.Sh SEE ALSO
.Xr zfs 8
.Sh BUGS
Report bugs to https://github.com/tilda-center/shappy/issues.
.Sh AUTHORS
Goran Mekić <meka@tilda.center>,
Rajko Dervišević <dervish13@tilda.center>,
Vladimir Jovin <vladimirjovin8@gmail.com>
