.Dd $Mdocdate: March 29 2022 $
.Dt SHAPPY 1
.Os
.Sh NAME
.Nm shappy
.Nd create snapshots and clean up unused ones
.Sh SYNOPSIS
.Nm shappy <snapshot|cleanup>
.Sh DESCRIPTION
.Pp
\fBShappy\fR is an open source program to make snapshotting of ZFS easy.
.Sh SEE ALSO
.Xr zfs 8
.Sh BUGS
Report bugs to https://github.com/tilda-center/shappy/issues.
.Sh AUTHORS
Goran Mekić <meka@tilda.center>,
Rajko Dervišević <dervish13@tilda.center>,
Vladimir Jovin <vladimirjovin8@gmail.com>
